# Generated by Django 5.1.6 on 2025-03-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
